name: Github Action with a cronjob trigger
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *" # Every 2 weeks
permissions:
  actions: write
jobs:
  cronjob-based-github-action:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@3eb47f21355191080dca0f7662d45c192d2ef64d # v2.0.7

