# Inspiration taken from: https://github.com/aquasecurity/trivy-checks/blob/main/.github/workflows/release.yaml
name: Refresh Trivy Checks Clone

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

env:
  VERSION: 0
  GH_USER: jahia-ci

jobs:
  build:
    name: Build DB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install oras
        run: |
          # upgrade to ORAS 1.0.0
          curl -LO https://github.com/oras-project/oras/releases/download/v1.0.0/oras_1.0.0_linux_amd64.tar.gz
          tar -xvf ./oras_1.0.0_linux_amd64.tar.gz

      - name: Download latest version of the DB
        run: |
          ./oras pull ghcr.io/aquasecurity/trivy-checks:${{ env.VERSION }}

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Upload assets to GHCR
        run: |
          ./oras version
          ./oras push ghcr.io/jahia/trivy-checks:${{ env.VERSION }} \
          --config /dev/null:application/vnd.cncf.openpolicyagent.config.v1+json \
          bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
